version: "3.4"

services:
  oclip:
    image: ghcr.io/hoeflechner/oclip:main
    container_name: oclip
    restart: unless-stopped
    ports:
      - "11435:11435"
    environment:
      - HALF=False
      - MODELNAME=hf-hub:apple/MobileCLIP-B-OpenCLIP
      - DEVICE=cuda
      - TIMEOUT=300
    build:
      context: .
      dockerfile: ./Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
